# Generated by Django 3.2.3 on 2021-05-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colungaHUB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
