# Generated by Django 3.2.3 on 2021-06-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colungaHUB_app', '0004_auto_20210622_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='flickr_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
